name: Check Merge Source
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [prod]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from preprod
        run: |
          if [ "$(gh pr view $PR_NUMBER --json headRefName -q '.headRefName')" != "preprod" ]; then
            echo "PR must be from preprd branch!"
            exit 1
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
