name: Check Merge Source
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [preprod, prod]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from main
        run: |
          if [ "$(gh pr view $PR_NUMBER --json baseRefName -q '.baseRefName')" != "main" ]; then
            echo "PR must be from main branch!"
            exit 1
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
