name: Check Merge Source Preprod to Prod
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [prod]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from main
        run: |
          if [ "${{ github.head_ref }}" != "preprod" ]; then
            echo "PR must be from preprod branch! Current source: ${{ github.head_ref }}"
            exit 1
          fi
