name: Deploy to Preprod

on:
  push:
    branches: [preprod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Preprod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_PREPROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Déploiement Préprod..."
            cd /home/florddev-preprod-sunnytown/htdocs/preprod.sunnytown.florddev.fr/

            git config --global --add safe.directory /home/florddev-preprod-sunnytown/htdocs/preprod.sunnytown.florddev.fr

            sudo chown -R florddev-preprod-sunnytown:florddev-preprod-sunnytown .
            sudo chmod -R 755 .
            sudo chmod -R 775 storage bootstrap/cache

            git pull origin preprod
            composer install --no-dev --optimize-autoloader

            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force

            npm ci
            npm run build

            sudo chown -R www-data:www-data public/build
