name: Deploy to Prod

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Déploiement Prod..."
            cd /home/florddev-sunnytown/htdocs/sunnytown.florddev.fr/
            git pull origin prod
            composer install --no-dev
            php artisan migrate --force
            php artisan db:seed
            npm install --production
            npm run build
