name: Deploy to Prod

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Déploiement Prod..."
            cd /home/florddev-sunnytown/htdocs/sunnytown.florddev.fr/

            # Configuration Git et permissions
            git config --global --add safe.directory /home/florddev-sunnytown/htdocs/sunnytown.florddev.fr
            sudo chown -R ${{ secrets.SSH_PROD_USER }}:florddev-sunnytown .
            sudo chmod -R 755 .

            # Reset et pull
            git reset --hard HEAD
            git clean -fd
            git pull origin prod

            # Créer et configurer les dossiers de logs AVANT tout
            sudo rm -rf storage/logs
            mkdir -p storage/logs
            touch storage/logs/laravel.log

            # Permissions pour storage et bootstrap/cache
            sudo chmod -R 777 storage bootstrap/cache
            sudo chown -R ${{ secrets.SSH_PROD_USER }}:florddev-sunnytown storage bootstrap/cache

            # Installation Composer avec suppression du cache
            php artisan config:clear || true
            php artisan cache:clear || true
            php artisan view:clear || true
            php artisan route:clear || true

            composer install --no-dev --optimize-autoloader --no-scripts

            # Post-install Composer scripts
            php artisan package:discover --ansi
            php artisan filament:upgrade

            # NPM
            sudo rm -rf node_modules package-lock.json
            npm install --omit=dev
            npm run build

            # Permissions finales
            sudo chown -R florddev-sunnytown:www-data storage bootstrap/cache public/build
            sudo chmod -R 775 storage bootstrap/cache public/build
            chmod 666 storage/logs/laravel.log

            # Cache Laravel
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force

            echo "✅ Déploiement Prod terminé avec succès!"
